#! /bin/sh

# bspwm config template
# Base16 Tomorrow by Chris Kempson (http://chriskempson.com)
# template by Luke Jones @luke-nukem

bspc config active_border_color \#b294bb
bspc config normal_border_color \#1d1f21
bspc config focused_border_color \#81a2be
bspc config presel_feedback_color \#b5bd68

bspc config normal_locked_border_color \#b5bd68
bspc config focused_locked_border_color \#b5bd68

bspc config normal_sticky_border_color \#de935f
bspc config focused_sticky_border_color \#de935f

bspc config normal_private_border_color \#282a2e
bspc config focused_private_border_color \#282a2e

bspc monitor eDP1 -d I II III IV V VI VII


bspc config border_width         5
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Firefox desktop=^1 follow=on focus=on
bspc rule -a Chromium desktop=^1 follow=on focus=on
bspc rule -a Thunderbird desktop=^2 follow=on focus=on
bspc rule -a kitty desktop=^3 follow=on focus=on
bspc rule -a Thunar desktop=^4 follow=on focus=on
bspc rule -a File-roller desktop=^4 follow=on focus=on
bspc rule -a Spotify desktop=^5 follow=on focus=on
bspc rule -a VirtualBox desktop=^6 follow=on focus=on

bspc rule -a Gimp follow=on floating=on
bspc rule -a Screenkey manage=off
bspc rule -a mplayer2 state=floating
bspc rule -a feh state=floating
bspc rule -a vlc state=floating
bspc rule -a mpv state=floating


# Autostart
xsetroot -cursor_name left_ptr

xset -b

compton &
dunst &
redshift &
nm-applet &
sxhkd &

feh --bg-scale ~/.wallpapers/current
$HOME/.config/polybar/launch.sh
