#! /bin/sh

# bspwm config template
# Base16 Tomorrow by Chris Kempson (http://chriskempson.com)
# template by Luke Jones @luke-nukem

bspc config active_border_color \#b4b7b4
bspc config normal_border_color \#373b41
bspc config focused_border_color \#cc6666
bspc config presel_feedback_color \#cc6666
bspc config normal_locked_border_color \#b5bd68
bspc config focused_locked_border_color \#b5bd68
bspc config normal_sticky_border_color \#de935f
bspc config focused_sticky_border_color \#de935f
bspc config normal_private_border_color \#282a2e
bspc config focused_private_border_color \#282a2e

if [[ $(hostname) == 'den' ]]; then
    bspc monitor DP-3  -d I II III
    bspc monitor DP-1  -d IV V VI
    bspc monitor DP-5  -d VII VIII IX
else
    bspc monitor eDP1 -d I II III IV V VI VII
fi
bspc monitor HDMI2 -d VIII


bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop=^1
bspc rule -a Thunderbird desktop=^2
bspc rule -a termine desktop=^3
bspc rule -a discord desktop=^4
bspc rule -a slack desktop=^4
bspc rule -a spotify desktop=^6
bspc rule -a VirtualBox desktop=^7

$HOME/.config/polybar/launch.sh
