[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#1d1f21"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#c5c8c6"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"
style = "Regular"

[font.offset]
x = 1
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.8

[window.padding]
x = 20
y = 20

[general]
live_config_reload = true

[terminal]
